// Data configuration file for Dr. Vinit's academic website

// Personal Information
const personalInfo = {
    name: "Dr. Vinit Katariya",
    title: "Assistant Professor",
    institution: "University of Wyoming",
    email: "vkatariy@uwyo.edu",
    facultyPage: "https://www.uwyo.edu/eecs/faculty-staff/faculty/vinit-katariya.html",
    profileImage: "pictures/bio/vinit_dark.png",
    bio: "Dr. Vinit Katariya is an assistant professor at the University of Wyoming. His research focuses on developing efficient and scalable machine learning algorithms for real-time applications. He holds a Ph.D. in Computer Science from a reputable university and has published numerous papers in top-tier conferences and journals. His work is primarily centered on vehicle trajectory prediction, anomaly detection in video surveillance, and edge AI for cyber-physical systems."
};

// Social Media Links
const socialLinks = {
    linkedin: "https://www.linkedin.com/in/vinitkatariya/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    googleScholar: "https://scholar.google.com/citations?user=jMPHBZMAAAAJ&hl=en",
    orcid: "https://orcid.org/0009-0003-9922-6041",
    github: "https://github.com/vinit-katariya"
};

// Publications Data
const publications = [
    // NOTE: Auto-generated by scripts/update_publications.py
    {
        title: "MoCLIP Motion-Aware Fine-Tuning and Distillation of CLIP for Human Motion Generation",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:MXK_kJrjxJIC",
        venue: "Proceedings of the Computer Vision and Pattern Recognition Conference, 2931-2941, 2025",
        type: "conference",
        year: 2025,
        visible: true,
        order: 0
    },

    {
        title: "VegaEdge: Edge AI confluence for real-time IoT-applications in highway safety",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:LkGwnXOMwfcC",
        venue: "Internet of Things 27, 101268, 2024",
        type: "article",
        year: 2024,
        visible: true,
        order: 1
    },

    {
        title: "Exploring Public's perception of safety and video surveillance technology: A survey approach",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:qjMakFHDy7sC",
        venue: "Technology in Society 78, 102641, 2024",
        type: "article",
        year: 2024,
        visible: true,
        order: 2
    },

    {
        title: "Towards Adaptive Human-centric Video Anomaly Detection: A Comprehensive Framework and A New Benchmark",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:kNdYIx-mwKoC",
        venue: "arXiv preprint arXiv:2408.14329, 2024",
        type: "preprint",
        year: 2024,
        visible: true,
        order: 3
    },

    {
        title: "A pov-based highway vehicle trajectory dataset and prediction architecture",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:ufrVoPGSRksC",
        venue: "IEEE Transactions on Intelligent Transportation Systems, 2024",
        type: "journal",
        year: 2024,
        visible: true,
        order: 4
    },

    {
        title: "Towards Adaptive Human-centric Video Anomaly Detection: A Comprehensive Framework and A New Benchmark",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:3fE2CSJIrl8C",
        venue: "arXiv e-prints, arXiv: 2408.14329, 2024",
        type: "preprint",
        year: 2024,
        visible: true,
        order: 5
    },

    {
        title: "PHEVA: A Privacy-preserving Human-centric Video Anomaly Detection Dataset",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:0EnyYjriUFMC",
        venue: "arXiv e-prints, arXiv: 2408.14329, 2024",
        type: "preprint",
        year: 2024,
        visible: false,
        order: 6
    },

    {
        title: "Distributed learning for automatic modulation recognition in bandwidth-limited networks",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:roLk4NBRz8UC",
        venue: "Signal Processing, Sensor/Information Fusion, and Target Recognition XXXIII …, 2024",
        type: "article",
        year: 2024,
        visible: false,
        order: 7
    },

    {
        title: "Enhancing automatic modulation recognition for iot applications using transformers",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:Se3iqnhoufwC",
        venue: "IoT 5 (2), 212-226, 2024",
        type: "article",
        year: 2024,
        visible: false,
        order: 8
    },

    {
        title: "Pheva: A privacy-preserving human-centric video anomaly detection dataset",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:hqOjcs7Dif8C",
        venue: "CoRR, 2024",
        type: "article",
        year: 2024,
        visible: false,
        order: 9
    },

    {
        title: "Vt-former: An exploratory study on vehicle trajectory prediction for highway surveillance through graph isomorphism and transformer",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:UebtZRa9Y70C",
        venue: "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern …, 2024",
        type: "conference",
        year: 2024,
        visible: false,
        order: 10
    },

    {
        title: "VegaEdge: Edge AI Confluence Anomaly Detection for Real-Time Highway IoT-Applications",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:Tyk-4Ss8FVUC",
        venue: "arXiv preprint arXiv:2311.07880, 2023",
        type: "preprint",
        year: 2023,
        visible: false,
        order: 11
    },

    {
        title: "VT-Former: An Exploratory Study on Vehicle Trajectory Prediction for Highway Surveillance through Graph Isomorphism and Transformer",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:d1gkVwhDpl0C",
        venue: "arXiv e-prints, arXiv: 2311.06623, 2023",
        type: "preprint",
        year: 2023,
        visible: false,
        order: 12
    },

    {
        title: "Understanding the challenges and opportunities of pose-based anomaly detection",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:u-x6o8ySG0sC",
        venue: "Proceedings of the 8th international Workshop on Sensor-Based Activity …, 2023",
        type: "conference",
        year: 2023,
        visible: false,
        order: 13
    },

    {
        title: "Pishgu: Universal path prediction network architecture for real-time cyber-physical edge systems",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:Y0pCki6q_DkC",
        venue: "Proceedings of the ACM/IEEE 14th International Conference on Cyber-Physical …, 2023",
        type: "conference",
        year: 2023,
        visible: false,
        order: 14
    },

    {
        title: "Demonstration of Pishgu: Universal Path Prediction Network Architecture for Real-time Cyber-physical Edge Systems",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:2osOgNQ5qMEC",
        venue: "Proceedings of the ACM/IEEE 14th International Conference on Cyber-Physical …, 2023",
        type: "conference",
        year: 2023,
        visible: false,
        order: 15
    },

    {
        title: "Advancing Highway Safety: Embedded-Edge AI for Real-Time Applications",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:IjCSPb-OGe4C",
        venue: "The University of North Carolina at Charlotte, 2023",
        type: "article",
        year: 2023,
        visible: false,
        order: 16
    },

    {
        title: "VT-Former: A Transformer-Based Vehicle Trajectory Prediction Approach for Intelligent Highway Transportation Systems.\" arXiv preprint",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:UeHWp8X0CEIC",
        venue: "arXiv preprint arXiv:2311.06623, 2023",
        type: "preprint",
        year: 2023,
        visible: false,
        order: 17
    },

    {
        title: "Deeptrack: Lightweight deep learning for vehicle trajectory prediction in highways",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:YsMSGLbcyi4C",
        venue: "IEEE Transactions on Intelligent Transportation Systems 23 (10), 18927-18936, 2022",
        type: "journal",
        year: 2022,
        visible: false,
        order: 18
    },

    {
        title: "Pishgu: Universal path prediction architecture through graph isomorphism and attentive convolution",
        url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=jMPHBZMAAAAJ&sortby=pubdate&citation_for_view=jMPHBZMAAAAJ:u5HHmVD_uO8C",
        venue: "arXiv preprint arXiv:2210.08057 2, 2022",
        type: "preprint",
        year: 2022,
        visible: false,
        order: 19
    }
];

// News Data
const newsData = [
    {
        id: "research-positions-2025",
        title: "Research Positions Available",
        date: "2025-09-20",
        description: "I have openings for passionate, talented, and self-motivated researchers at both the MS and PhD levels. MS students should reach out directly to discuss available positions. Prospective PhD students should review the posted opportunity details and contact me.",
        image: "pictures/eecs_uwyo_logo.jpg",
        category: "opportunity",
        featured: true,
        flash: true,
        pdfLink: "pictures/files/research%20opportunity.pdf",
        contactEmail: "vkatariy@uwyo.edu"
    },
    {
        id: "icmla-2025",
        title: "New Publication Accepted (ICMLA) 2025",
        date: "2025-09-14",
        description: "Our paper \"Adversarially-Refined VQ-GAN with Dense Motion Tokenization for Spatio-Temporal Heatmaps\" has been accepted at the IEEE International Conference on Machine Learning and Applications (ICMLA) 2025.",
        extendedDescription: "This work addresses continuous human motion understanding through an adversarially-refined VQ-GAN framework that compresses spatio-temporal heatmaps while preserving fine-grained motion traces.",
        image: "pictures/ICMLA.png",
        category: "publication",
        featured: true
    },
    {
        id: "speaking-engagement-2025",
        title: "EECS Advisory Board Presentation",
        date: "2025-09-12",
        description: "I was honoured to present my research and discuss future directions and plans to the Advisory board of EECS department at University of Wyoming",
        image: "pictures/eecs_uwyo_logo.jpg",
        category: "speaking",
        featured: true
    },
    {
        id: "Uwyo-joining-19Aug2025",
        title: "Joined University of Wyoming",
        date: "2025-08-19",
        description: "Joined the University of Wyoming as an Assistant Professor with a joint appointment in the Department of Electrical Engineering and Computer Science (EECS) and the School of Computing (SoC).",
        image: "https://www.uwyo.edu/eecs/_files/images/eerb.jpg",
        category: "news",
        featured: true
    },
    // {
    //     id: "conference-talk-2025",
    //     title: "Invited Talk at National Conference",
    //     date: "2025-02-28",
    //     description: "Dr. Katariya gave an invited talk on his work at the annual conference of the American Association for Science.",
    //     image: "https://placehold.co/200x120/E5E7EB/4B5563?text=Conference+Talk",
    //     category: "speaking",
    //     featured: false
    // },
    // {
    //     id: "funding-2024",
    //     title: "New Funding for Sustainable Energy Project",
    //     date: "2024-11-01",
    //     description: "The team secured a new grant to study sustainable energy solutions for the next three years.",
    //     image: "https://placehold.co/200x120/E5E7EB/4B5563?text=Funding+Grant",
    //     category: "funding",
    //     featured: false
    // },
];

// Research Areas
const researchAreas = [
    "Artificial Intelligence",
    "Computer Vision",
    "IoT Systems",
    "Public Safety",
    "Community Engagement",
    "Public Perception of AI for Safety",
    "Vehicle Trajectory Prediction",
    "Anomaly Detection",
    "Edge AI",
    "Cyber-Physical Systems",
    "Machine Learning",
    "Deep Learning"
];

// Research Projects
const researchProjects = [
    {
        id: "ai-urban-infrastructure",
        title: "AI for Urban Infras.",
        subtitle: "Pedestrian Safety",
        summary: "Studying the impact of soft infrastructure changes on pedestrian safety through computer vision analysis in Minneapolis.",
        description: "Developed an AI-based assessment framework that taps into municipal CCTV networks or existing video archives to uncover how street-level changes influence pedestrian outcomes.",
        image: "pictures/research/Speed_AI_pipeline.png",
        focusArea: "Urban AI",
        detailPage: "research/ai-urban-infrastructure.html",
        highlights: [
            "Use CCTV cameras or existing videos for rapid deployment",
            "Easily integrates with new or legacy CCTV infrastructure",
            "Cost-effective and highly scalable architecture",
            "AI-driven analytics to extract actionable insights"
        ],
        insights: [
            "Speed Analysis: Vehicle speed monitoring and traffic trend discovery",
            "Behavioral Insights: Stop behavior and motion direction profiling"
        ],
        partners: [
            {
                name: "UNC Charlotte",
                logo: "pictures/logos/unc_charlotte.svg"
            },
            {
                name: "University of Minnesota",
                logo: "pictures/logos/university_of_minnesota.svg"
            },
            {
                name: "MnDOT",
                logo: "pictures/logos/mndot.svg"
            }
        ],
        funders: [
            {
                name: "MnDOT",
                logo: "pictures/logos/mndot.svg"
            }
        ]
    },
    {
        id: "highway-workzone-safety",
        title: "Highway Workzone Safety",
        subtitle: "Real-time Edge AI",
        summary: "Edge AI pipeline for real-time trajectory tracking and anomaly prediction in highway workzones.",
        description: "Deploying lightweight perception models to monitor active workzones, anticipate unsafe maneuvers, and alert crews before incidents escalate.",
        image: "pictures/research/highway_workzone/WZ_time.png",
        focusArea: "Edge AI",
        detailPage: "research/highway-workzone-safety.html",
        highlights: [
            "Edge-deployable multi-modal sensing stack",
            "Trajectory forecasting tuned for congested corridors",
            "Anomaly scoring tailored to highway workzone conditions"
        ],
        insights: [
            "Predictive risk alerts for field crews",
            "Data pipeline ready for DOT-scale integrations"
        ],
        partners: [
            {
                name: "UNC Charlotte",
                logo: "pictures/logos/unc_charlotte.svg"
            },
            {
                name: "University of Minnesota",
                logo: "pictures/logos/university_of_minnesota.svg"
            },
            {
                name: "NSF",
                logo: "pictures/logos/nsf.svg"
            }
        ],
        funders: [
            {
                name: "NSF",
                logo: "pictures/logos/nsf.svg"
            }
        ]
    },
    {
        id: "rural-roundabouts",
        title: "Rural Roundabouts",
        subtitle: "Vision for Safer Junctions",
        summary: "AI-enabled analytics guiding new rural roundabout designs with speed behavior insights and occupancy tracking.",
        description: "We evaluate prototype rural roundabout configurations using edge perception to measure approach speeds, circulating occupancy, and compliance. Results inform SRF Consulting and MnDOT on design refinements for high-speed corridors.",
        image: "pictures/research/rab/roundabout_overview.svg",
        focusArea: "Transportation AI",
        detailPage: "research/rural-roundabouts.html",
        highlights: [
            "New rural roundabout geometry evaluation",
            "Speed behavior modelling across approaches",
            "AI-based speed estimation at the edge",
            "Occupancy detection for circulating traffic"
        ],
        insights: [
            "Vision analytics tuned for low-light rural settings",
            "Configurable dashboards for DOT design reviews"
        ],
        partners: [
            {
                name: "SRF Consulting",
                logo: "pictures/logos/srf_consulting.svg"
            },
            {
                name: "UNC Charlotte",
                logo: "pictures/logos/unc_charlotte.svg"
            },
            {
                name: "University of Minnesota",
                logo: "pictures/logos/university_of_minnesota.svg"
            }
        ],
        funders: [
            {
                name: "MnDOT",
                logo: "pictures/logos/mndot.svg"
            }
        ]
    }
];

// Website Configuration
const siteConfig = {
    title: "Dr. Vinit - Academic Website",
    description: "Official academic website of Dr. Vinit Katariya, Assistant Professor at the University of Wyoming",
    author: "Dr. Vinit Katariya",
    keywords: "artificial intelligence, computer vision, IoT, machine learning, University of Wyoming",
    version: "2.0.0"
};

// CV Data
const cvData = {
    introduction: "A detailed overview of Dr. Katariya's academic background, research portfolio, teaching, and service.",
    education: [
        {
            degree: "Ph.D. in Electrical Engineering",
            institution: "University of North Carolina at Charlotte",
            location: "Charlotte, NC, USA",
            year: "December 2023",
            details: "Dissertation: Advancing Highway Safety: Embedded-edge AI for Real-time Applications"
        },
        {
            degree: "M.S. in Electrical Engineering",
            institution: "University of North Carolina at Charlotte",
            location: "Charlotte, NC, USA",
            year: "May 2016",
            details: "Project: A Novel RF (XBEE) and IR LOS Collaborative V2V Navigation Technique"
        },
        {
            degree: "B.E. in Electronics",
            institution: "Savitribai Phule Pune University",
            location: "Pune, Maharashtra, India",
            year: "May 2012",
            details: "Project: Auto-switching of Devices Using Brain Waves"
        }
    ],
    academicPositions: [
        {
            title: "Assistant Professor",
            organization: "<a href=\"https://www.uwyo.edu/eecs/faculty-staff/faculty/vinit-katariya.html\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-blue-700 hover:underline\">Department of Electrical Engineering and Computer Science</a> & School of Computing, University of Wyoming",
            period: "August 2025 – Present"
        },
        {
            title: "Postdoctoral Researcher",
            organization: "Department of Electrical and Computer Engineering, UNC Charlotte",
            period: "October 2023 – August 2025",
            bullets: [
                "Led AI development for MnDOT intersection safety initiatives with multi-institutional teams.",
                "Designed pipelines for trajectory prediction, anomaly detection, and sensor fusion across RGB, WiFi, and depth data.",
                "Supervised 3 Ph.D. and 6 M.S. students while contributing to multi-hundred-thousand-dollar grants."
            ]
        },
        {
            title: "Graduate Research Assistant",
            organization: "Department of Electrical and Computer Engineering, UNC Charlotte",
            period: "January 2018 – October 2023",
            bullets: [
                "Developed lightweight ML/DL algorithms for real-time video analysis and highway safety applications.",
                "Built context-aware trajectory prediction models such as Pishgu and PishguVe for cyber-physical systems.",
                "Integrated AI pipelines with VR/AR and wearable alerts while mentoring graduate students."
            ]
        }
    ],
    teachingExperience: [
        {
            role: "Instructor / Guest Lecturer",
            organization: "UNC Charlotte",
            period: "Spring 2024",
            courses: ["Perceptron and Vectorization – contemporary AI applications"]
        },
        {
            role: "Teaching Assistant",
            organization: "UNC Charlotte",
            period: "2018 – 2021",
            courses: [
                "Electromagnetic and Electronic Devices (ECGR 3156)",
                "Computer Engineering Programming II (ECGR 2104)",
                "Logic System Design (ECGR 2181)",
                "Digital Signal Processing (ECGR 4124/5124)"
            ]
        }
    ],
    industryExperience: [
        {
            role: "Software Engineer",
            organization: "Sears Holdings Management Corporation",
            period: "June 2016 – May 2017",
            bullets: [
                "Built Python-based sensor systems to monitor store traffic with ~80% accuracy and integrated SQL analytics.",
                "Implemented image-comparison workflows within a Meteor JavaScript application for low-resolution camera feeds."
            ]
        },
        {
            role: "Software Engineer Intern",
            organization: "Sears Holdings Management Corporation",
            period: "May 2015 – August 2015",
            bullets: [
                "Developed MQTT-based client solutions enabling OTA updates for ARM Cortex-M4 IoT devices."
            ]
        }
    ],
    awards: [
        "Best Demo Award – ICCPS (2023)",
        "UNC Charlotte Graduate School Summer Scholarship (2022)",
        "Ph.D. Mentor, Mentor Collective (2021 – 2023)",
        "IEEE Member #93133990 (2014 – Present)"
    ],
    professionalService: [
        "Program Committee / Reviewer: IEEE ICMLA, CVPR, ICCV",
        "Reviewer: IEEE Access, IEEE Transactions on Intelligent Transportation Systems, IEEE Wireless Communications Letters",
        "Reviewer: International Journal of Cognitive Computing in Engineering; Springer AI, Cluster Computing, Operations Research Forum",
        "Artifact Evaluation Committee Member: IEEE ICCPS"
    ],
    downloadUrl: "pictures/files/Curriculum%20Vitae_Vinit_Katariya.pdf"
};

// Export data for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        personalInfo,
        socialLinks,
        publications,
        newsData,
        researchAreas,
        siteConfig,
        cvData
    };
}
