name: Update Publications

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install scraper dependencies
        run: pip install -r requirements.txt

      - name: Refresh publications data
        run: python scripts/update_publications.py

      - name: Commit updated publications
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update publications data from Google Scholar
          file_pattern: data.js
